// Automatically generated by scripts/steamproxygen.py, do not modify!!!
#ifndef STEAMFRIENDSPROXY015_H
#define STEAMFRIENDSPROXY015_H

#include "steamproxy.h"
#include <steam_old/isteamfriends015.h>

class SteamFriendsProxy015 final : public ISteamFriends015
{
    ISteamFriends015 *m_original;
    SteamFriendsProxy *m_proxy;

public:
    SteamFriendsProxy015(ISteamFriends015 *original, SteamFriendsProxy *proxy)
        : m_original{ original }
        , m_proxy{ proxy }
    {
    }

    const char * GetPersonaName() override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetPersonaName>(m_original);
            if constexpr (requires { p->GetPersonaName(o); })
                return p->GetPersonaName(o);
            else
                return o();
        }(m_proxy);
    }

    SteamAPICall_t SetPersonaName(const char *pchPersonaName) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::SetPersonaName>(m_original);
            if constexpr (requires { p->SetPersonaName(o, pchPersonaName); })
                return p->SetPersonaName(o, pchPersonaName);
            else
                return o(pchPersonaName);
        }(m_proxy);
    }

    EPersonaState GetPersonaState() override
    {
        return [&](auto p) -> EPersonaState
        {
            auto o = MakeOrig<&ISteamFriends015::GetPersonaState>(m_original);
            if constexpr (requires { p->GetPersonaState(o); })
                return p->GetPersonaState(o);
            else
                return o();
        }(m_proxy);
    }

    int GetFriendCount(int iFriendFlags) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendCount>(m_original);
            if constexpr (requires { p->GetFriendCount(o, iFriendFlags); })
                return p->GetFriendCount(o, iFriendFlags);
            else
                return o(iFriendFlags);
        }(m_proxy);
    }

    CSteamID GetFriendByIndex(int iFriend, int iFriendFlags) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendByIndex>(m_original);
            if constexpr (requires { p->GetFriendByIndex(o, iFriend, iFriendFlags); })
                return p->GetFriendByIndex(o, iFriend, iFriendFlags);
            else
                return o(iFriend, iFriendFlags);
        }(m_proxy);
    }

    EFriendRelationship GetFriendRelationship(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> EFriendRelationship
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendRelationship>(m_original);
            if constexpr (requires { p->GetFriendRelationship(o, steamIDFriend); })
                return p->GetFriendRelationship(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    EPersonaState GetFriendPersonaState(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> EPersonaState
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendPersonaState>(m_original);
            if constexpr (requires { p->GetFriendPersonaState(o, steamIDFriend); })
                return p->GetFriendPersonaState(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    const char * GetFriendPersonaName(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendPersonaName>(m_original);
            if constexpr (requires { p->GetFriendPersonaName(o, steamIDFriend); })
                return p->GetFriendPersonaName(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    bool GetFriendGamePlayed(CSteamID steamIDFriend, FriendGameInfo_t *pFriendGameInfo) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendGamePlayed>(m_original);
            if constexpr (requires { p->GetFriendGamePlayed(o, steamIDFriend, pFriendGameInfo); })
                return p->GetFriendGamePlayed(o, steamIDFriend, pFriendGameInfo);
            else
                return o(steamIDFriend, pFriendGameInfo);
        }(m_proxy);
    }

    const char * GetFriendPersonaNameHistory(CSteamID steamIDFriend, int iPersonaName) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendPersonaNameHistory>(m_original);
            if constexpr (requires { p->GetFriendPersonaNameHistory(o, steamIDFriend, iPersonaName); })
                return p->GetFriendPersonaNameHistory(o, steamIDFriend, iPersonaName);
            else
                return o(steamIDFriend, iPersonaName);
        }(m_proxy);
    }

    int GetFriendSteamLevel(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendSteamLevel>(m_original);
            if constexpr (requires { p->GetFriendSteamLevel(o, steamIDFriend); })
                return p->GetFriendSteamLevel(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    const char * GetPlayerNickname(CSteamID steamIDPlayer) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetPlayerNickname>(m_original);
            if constexpr (requires { p->GetPlayerNickname(o, steamIDPlayer); })
                return p->GetPlayerNickname(o, steamIDPlayer);
            else
                return o(steamIDPlayer);
        }(m_proxy);
    }

    int GetFriendsGroupCount() override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendsGroupCount>(m_original);
            if constexpr (requires { p->GetFriendsGroupCount(o); })
                return p->GetFriendsGroupCount(o);
            else
                return o();
        }(m_proxy);
    }

    FriendsGroupID_t GetFriendsGroupIDByIndex(int iFG) override
    {
        return [&](auto p) -> FriendsGroupID_t
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendsGroupIDByIndex>(m_original);
            if constexpr (requires { p->GetFriendsGroupIDByIndex(o, iFG); })
                return p->GetFriendsGroupIDByIndex(o, iFG);
            else
                return o(iFG);
        }(m_proxy);
    }

    const char * GetFriendsGroupName(FriendsGroupID_t friendsGroupID) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendsGroupName>(m_original);
            if constexpr (requires { p->GetFriendsGroupName(o, friendsGroupID); })
                return p->GetFriendsGroupName(o, friendsGroupID);
            else
                return o(friendsGroupID);
        }(m_proxy);
    }

    int GetFriendsGroupMembersCount(FriendsGroupID_t friendsGroupID) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendsGroupMembersCount>(m_original);
            if constexpr (requires { p->GetFriendsGroupMembersCount(o, friendsGroupID); })
                return p->GetFriendsGroupMembersCount(o, friendsGroupID);
            else
                return o(friendsGroupID);
        }(m_proxy);
    }

    void GetFriendsGroupMembersList(FriendsGroupID_t friendsGroupID, CSteamID *pOutSteamIDMembers, int nMembersCount) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendsGroupMembersList>(m_original);
            if constexpr (requires { p->GetFriendsGroupMembersList(o, friendsGroupID, pOutSteamIDMembers, nMembersCount); })
                p->GetFriendsGroupMembersList(o, friendsGroupID, pOutSteamIDMembers, nMembersCount);
            else
                o(friendsGroupID, pOutSteamIDMembers, nMembersCount);
        }(m_proxy);
    }

    bool HasFriend(CSteamID steamIDFriend, int iFriendFlags) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::HasFriend>(m_original);
            if constexpr (requires { p->HasFriend(o, steamIDFriend, iFriendFlags); })
                return p->HasFriend(o, steamIDFriend, iFriendFlags);
            else
                return o(steamIDFriend, iFriendFlags);
        }(m_proxy);
    }

    int GetClanCount() override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanCount>(m_original);
            if constexpr (requires { p->GetClanCount(o); })
                return p->GetClanCount(o);
            else
                return o();
        }(m_proxy);
    }

    CSteamID GetClanByIndex(int iClan) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanByIndex>(m_original);
            if constexpr (requires { p->GetClanByIndex(o, iClan); })
                return p->GetClanByIndex(o, iClan);
            else
                return o(iClan);
        }(m_proxy);
    }

    const char * GetClanName(CSteamID steamIDClan) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanName>(m_original);
            if constexpr (requires { p->GetClanName(o, steamIDClan); })
                return p->GetClanName(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    const char * GetClanTag(CSteamID steamIDClan) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanTag>(m_original);
            if constexpr (requires { p->GetClanTag(o, steamIDClan); })
                return p->GetClanTag(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    bool GetClanActivityCounts(CSteamID steamIDClan, int *pnOnline, int *pnInGame, int *pnChatting) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanActivityCounts>(m_original);
            if constexpr (requires { p->GetClanActivityCounts(o, steamIDClan, pnOnline, pnInGame, pnChatting); })
                return p->GetClanActivityCounts(o, steamIDClan, pnOnline, pnInGame, pnChatting);
            else
                return o(steamIDClan, pnOnline, pnInGame, pnChatting);
        }(m_proxy);
    }

    SteamAPICall_t DownloadClanActivityCounts(CSteamID *psteamIDClans, int cClansToRequest) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::DownloadClanActivityCounts>(m_original);
            if constexpr (requires { p->DownloadClanActivityCounts(o, psteamIDClans, cClansToRequest); })
                return p->DownloadClanActivityCounts(o, psteamIDClans, cClansToRequest);
            else
                return o(psteamIDClans, cClansToRequest);
        }(m_proxy);
    }

    int GetFriendCountFromSource(CSteamID steamIDSource) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendCountFromSource>(m_original);
            if constexpr (requires { p->GetFriendCountFromSource(o, steamIDSource); })
                return p->GetFriendCountFromSource(o, steamIDSource);
            else
                return o(steamIDSource);
        }(m_proxy);
    }

    CSteamID GetFriendFromSourceByIndex(CSteamID steamIDSource, int iFriend) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendFromSourceByIndex>(m_original);
            if constexpr (requires { p->GetFriendFromSourceByIndex(o, steamIDSource, iFriend); })
                return p->GetFriendFromSourceByIndex(o, steamIDSource, iFriend);
            else
                return o(steamIDSource, iFriend);
        }(m_proxy);
    }

    bool IsUserInSource(CSteamID steamIDUser, CSteamID steamIDSource) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::IsUserInSource>(m_original);
            if constexpr (requires { p->IsUserInSource(o, steamIDUser, steamIDSource); })
                return p->IsUserInSource(o, steamIDUser, steamIDSource);
            else
                return o(steamIDUser, steamIDSource);
        }(m_proxy);
    }

    void SetInGameVoiceSpeaking(CSteamID steamIDUser, bool bSpeaking) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::SetInGameVoiceSpeaking>(m_original);
            if constexpr (requires { p->SetInGameVoiceSpeaking(o, steamIDUser, bSpeaking); })
                p->SetInGameVoiceSpeaking(o, steamIDUser, bSpeaking);
            else
                o(steamIDUser, bSpeaking);
        }(m_proxy);
    }

    void ActivateGameOverlay(const char *pchDialog) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::ActivateGameOverlay>(m_original);
            if constexpr (requires { p->ActivateGameOverlay(o, pchDialog); })
                p->ActivateGameOverlay(o, pchDialog);
            else
                o(pchDialog);
        }(m_proxy);
    }

    void ActivateGameOverlayToUser(const char *pchDialog, CSteamID steamID) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::ActivateGameOverlayToUser>(m_original);
            if constexpr (requires { p->ActivateGameOverlayToUser(o, pchDialog, steamID); })
                p->ActivateGameOverlayToUser(o, pchDialog, steamID);
            else
                o(pchDialog, steamID);
        }(m_proxy);
    }

    void ActivateGameOverlayToWebPage(const char *pchURL) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::ActivateGameOverlayToWebPage>(m_original);
            if constexpr (requires { p->ActivateGameOverlayToWebPage(o, pchURL); })
                p->ActivateGameOverlayToWebPage(o, pchURL);
            else
                o(pchURL);
        }(m_proxy);
    }

    void ActivateGameOverlayToStore(AppId_t nAppID, EOverlayToStoreFlag eFlag) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::ActivateGameOverlayToStore>(m_original);
            if constexpr (requires { p->ActivateGameOverlayToStore(o, nAppID, eFlag); })
                p->ActivateGameOverlayToStore(o, nAppID, eFlag);
            else
                o(nAppID, eFlag);
        }(m_proxy);
    }

    void SetPlayedWith(CSteamID steamIDUserPlayedWith) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::SetPlayedWith>(m_original);
            if constexpr (requires { p->SetPlayedWith(o, steamIDUserPlayedWith); })
                p->SetPlayedWith(o, steamIDUserPlayedWith);
            else
                o(steamIDUserPlayedWith);
        }(m_proxy);
    }

    void ActivateGameOverlayInviteDialog(CSteamID steamIDLobby) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::ActivateGameOverlayInviteDialog>(m_original);
            if constexpr (requires { p->ActivateGameOverlayInviteDialog(o, steamIDLobby); })
                p->ActivateGameOverlayInviteDialog(o, steamIDLobby);
            else
                o(steamIDLobby);
        }(m_proxy);
    }

    int GetSmallFriendAvatar(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetSmallFriendAvatar>(m_original);
            if constexpr (requires { p->GetSmallFriendAvatar(o, steamIDFriend); })
                return p->GetSmallFriendAvatar(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    int GetMediumFriendAvatar(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetMediumFriendAvatar>(m_original);
            if constexpr (requires { p->GetMediumFriendAvatar(o, steamIDFriend); })
                return p->GetMediumFriendAvatar(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    int GetLargeFriendAvatar(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetLargeFriendAvatar>(m_original);
            if constexpr (requires { p->GetLargeFriendAvatar(o, steamIDFriend); })
                return p->GetLargeFriendAvatar(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    bool RequestUserInformation(CSteamID steamIDUser, bool bRequireNameOnly) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::RequestUserInformation>(m_original);
            if constexpr (requires { p->RequestUserInformation(o, steamIDUser, bRequireNameOnly); })
                return p->RequestUserInformation(o, steamIDUser, bRequireNameOnly);
            else
                return o(steamIDUser, bRequireNameOnly);
        }(m_proxy);
    }

    SteamAPICall_t RequestClanOfficerList(CSteamID steamIDClan) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::RequestClanOfficerList>(m_original);
            if constexpr (requires { p->RequestClanOfficerList(o, steamIDClan); })
                return p->RequestClanOfficerList(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    CSteamID GetClanOwner(CSteamID steamIDClan) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanOwner>(m_original);
            if constexpr (requires { p->GetClanOwner(o, steamIDClan); })
                return p->GetClanOwner(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    int GetClanOfficerCount(CSteamID steamIDClan) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanOfficerCount>(m_original);
            if constexpr (requires { p->GetClanOfficerCount(o, steamIDClan); })
                return p->GetClanOfficerCount(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    CSteamID GetClanOfficerByIndex(CSteamID steamIDClan, int iOfficer) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanOfficerByIndex>(m_original);
            if constexpr (requires { p->GetClanOfficerByIndex(o, steamIDClan, iOfficer); })
                return p->GetClanOfficerByIndex(o, steamIDClan, iOfficer);
            else
                return o(steamIDClan, iOfficer);
        }(m_proxy);
    }

    uint32 GetUserRestrictions() override
    {
        return [&](auto p) -> uint32
        {
            auto o = MakeOrig<&ISteamFriends015::GetUserRestrictions>(m_original);
            if constexpr (requires { p->GetUserRestrictions(o); })
                return p->GetUserRestrictions(o);
            else
                return o();
        }(m_proxy);
    }

    bool SetRichPresence(const char *pchKey, const char *pchValue) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::SetRichPresence>(m_original);
            if constexpr (requires { p->SetRichPresence(o, pchKey, pchValue); })
                return p->SetRichPresence(o, pchKey, pchValue);
            else
                return o(pchKey, pchValue);
        }(m_proxy);
    }

    void ClearRichPresence() override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::ClearRichPresence>(m_original);
            if constexpr (requires { p->ClearRichPresence(o); })
                p->ClearRichPresence(o);
            else
                o();
        }(m_proxy);
    }

    const char * GetFriendRichPresence(CSteamID steamIDFriend, const char *pchKey) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendRichPresence>(m_original);
            if constexpr (requires { p->GetFriendRichPresence(o, steamIDFriend, pchKey); })
                return p->GetFriendRichPresence(o, steamIDFriend, pchKey);
            else
                return o(steamIDFriend, pchKey);
        }(m_proxy);
    }

    int GetFriendRichPresenceKeyCount(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendRichPresenceKeyCount>(m_original);
            if constexpr (requires { p->GetFriendRichPresenceKeyCount(o, steamIDFriend); })
                return p->GetFriendRichPresenceKeyCount(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    const char * GetFriendRichPresenceKeyByIndex(CSteamID steamIDFriend, int iKey) override
    {
        return [&](auto p) -> const char *
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendRichPresenceKeyByIndex>(m_original);
            if constexpr (requires { p->GetFriendRichPresenceKeyByIndex(o, steamIDFriend, iKey); })
                return p->GetFriendRichPresenceKeyByIndex(o, steamIDFriend, iKey);
            else
                return o(steamIDFriend, iKey);
        }(m_proxy);
    }

    void RequestFriendRichPresence(CSteamID steamIDFriend) override
    {
        [&](auto p) -> void
        {
            auto o = MakeOrig<&ISteamFriends015::RequestFriendRichPresence>(m_original);
            if constexpr (requires { p->RequestFriendRichPresence(o, steamIDFriend); })
                p->RequestFriendRichPresence(o, steamIDFriend);
            else
                o(steamIDFriend);
        }(m_proxy);
    }

    bool InviteUserToGame(CSteamID steamIDFriend, const char *pchConnectString) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::InviteUserToGame>(m_original);
            if constexpr (requires { p->InviteUserToGame(o, steamIDFriend, pchConnectString); })
                return p->InviteUserToGame(o, steamIDFriend, pchConnectString);
            else
                return o(steamIDFriend, pchConnectString);
        }(m_proxy);
    }

    int GetCoplayFriendCount() override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetCoplayFriendCount>(m_original);
            if constexpr (requires { p->GetCoplayFriendCount(o); })
                return p->GetCoplayFriendCount(o);
            else
                return o();
        }(m_proxy);
    }

    CSteamID GetCoplayFriend(int iCoplayFriend) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetCoplayFriend>(m_original);
            if constexpr (requires { p->GetCoplayFriend(o, iCoplayFriend); })
                return p->GetCoplayFriend(o, iCoplayFriend);
            else
                return o(iCoplayFriend);
        }(m_proxy);
    }

    int GetFriendCoplayTime(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendCoplayTime>(m_original);
            if constexpr (requires { p->GetFriendCoplayTime(o, steamIDFriend); })
                return p->GetFriendCoplayTime(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    AppId_t GetFriendCoplayGame(CSteamID steamIDFriend) override
    {
        return [&](auto p) -> AppId_t
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendCoplayGame>(m_original);
            if constexpr (requires { p->GetFriendCoplayGame(o, steamIDFriend); })
                return p->GetFriendCoplayGame(o, steamIDFriend);
            else
                return o(steamIDFriend);
        }(m_proxy);
    }

    SteamAPICall_t JoinClanChatRoom(CSteamID steamIDClan) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::JoinClanChatRoom>(m_original);
            if constexpr (requires { p->JoinClanChatRoom(o, steamIDClan); })
                return p->JoinClanChatRoom(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    bool LeaveClanChatRoom(CSteamID steamIDClan) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::LeaveClanChatRoom>(m_original);
            if constexpr (requires { p->LeaveClanChatRoom(o, steamIDClan); })
                return p->LeaveClanChatRoom(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    int GetClanChatMemberCount(CSteamID steamIDClan) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanChatMemberCount>(m_original);
            if constexpr (requires { p->GetClanChatMemberCount(o, steamIDClan); })
                return p->GetClanChatMemberCount(o, steamIDClan);
            else
                return o(steamIDClan);
        }(m_proxy);
    }

    CSteamID GetChatMemberByIndex(CSteamID steamIDClan, int iUser) override
    {
        return [&](auto p) -> CSteamID
        {
            auto o = MakeOrig<&ISteamFriends015::GetChatMemberByIndex>(m_original);
            if constexpr (requires { p->GetChatMemberByIndex(o, steamIDClan, iUser); })
                return p->GetChatMemberByIndex(o, steamIDClan, iUser);
            else
                return o(steamIDClan, iUser);
        }(m_proxy);
    }

    bool SendClanChatMessage(CSteamID steamIDClanChat, const char *pchText) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::SendClanChatMessage>(m_original);
            if constexpr (requires { p->SendClanChatMessage(o, steamIDClanChat, pchText); })
                return p->SendClanChatMessage(o, steamIDClanChat, pchText);
            else
                return o(steamIDClanChat, pchText);
        }(m_proxy);
    }

    int GetClanChatMessage(CSteamID steamIDClanChat, int iMessage, void *prgchText, int cchTextMax, EChatEntryType *peChatEntryType, CSteamID *psteamidChatter) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetClanChatMessage>(m_original);
            if constexpr (requires { p->GetClanChatMessage(o, steamIDClanChat, iMessage, prgchText, cchTextMax, peChatEntryType, psteamidChatter); })
                return p->GetClanChatMessage(o, steamIDClanChat, iMessage, prgchText, cchTextMax, peChatEntryType, psteamidChatter);
            else
                return o(steamIDClanChat, iMessage, prgchText, cchTextMax, peChatEntryType, psteamidChatter);
        }(m_proxy);
    }

    bool IsClanChatAdmin(CSteamID steamIDClanChat, CSteamID steamIDUser) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::IsClanChatAdmin>(m_original);
            if constexpr (requires { p->IsClanChatAdmin(o, steamIDClanChat, steamIDUser); })
                return p->IsClanChatAdmin(o, steamIDClanChat, steamIDUser);
            else
                return o(steamIDClanChat, steamIDUser);
        }(m_proxy);
    }

    bool IsClanChatWindowOpenInSteam(CSteamID steamIDClanChat) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::IsClanChatWindowOpenInSteam>(m_original);
            if constexpr (requires { p->IsClanChatWindowOpenInSteam(o, steamIDClanChat); })
                return p->IsClanChatWindowOpenInSteam(o, steamIDClanChat);
            else
                return o(steamIDClanChat);
        }(m_proxy);
    }

    bool OpenClanChatWindowInSteam(CSteamID steamIDClanChat) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::OpenClanChatWindowInSteam>(m_original);
            if constexpr (requires { p->OpenClanChatWindowInSteam(o, steamIDClanChat); })
                return p->OpenClanChatWindowInSteam(o, steamIDClanChat);
            else
                return o(steamIDClanChat);
        }(m_proxy);
    }

    bool CloseClanChatWindowInSteam(CSteamID steamIDClanChat) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::CloseClanChatWindowInSteam>(m_original);
            if constexpr (requires { p->CloseClanChatWindowInSteam(o, steamIDClanChat); })
                return p->CloseClanChatWindowInSteam(o, steamIDClanChat);
            else
                return o(steamIDClanChat);
        }(m_proxy);
    }

    bool SetListenForFriendsMessages(bool bInterceptEnabled) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::SetListenForFriendsMessages>(m_original);
            if constexpr (requires { p->SetListenForFriendsMessages(o, bInterceptEnabled); })
                return p->SetListenForFriendsMessages(o, bInterceptEnabled);
            else
                return o(bInterceptEnabled);
        }(m_proxy);
    }

    bool ReplyToFriendMessage(CSteamID steamIDFriend, const char *pchMsgToSend) override
    {
        return [&](auto p) -> bool
        {
            auto o = MakeOrig<&ISteamFriends015::ReplyToFriendMessage>(m_original);
            if constexpr (requires { p->ReplyToFriendMessage(o, steamIDFriend, pchMsgToSend); })
                return p->ReplyToFriendMessage(o, steamIDFriend, pchMsgToSend);
            else
                return o(steamIDFriend, pchMsgToSend);
        }(m_proxy);
    }

    int GetFriendMessage(CSteamID steamIDFriend, int iMessageID, void *pvData, int cubData, EChatEntryType *peChatEntryType) override
    {
        return [&](auto p) -> int
        {
            auto o = MakeOrig<&ISteamFriends015::GetFriendMessage>(m_original);
            if constexpr (requires { p->GetFriendMessage(o, steamIDFriend, iMessageID, pvData, cubData, peChatEntryType); })
                return p->GetFriendMessage(o, steamIDFriend, iMessageID, pvData, cubData, peChatEntryType);
            else
                return o(steamIDFriend, iMessageID, pvData, cubData, peChatEntryType);
        }(m_proxy);
    }

    SteamAPICall_t GetFollowerCount(CSteamID steamID) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::GetFollowerCount>(m_original);
            if constexpr (requires { p->GetFollowerCount(o, steamID); })
                return p->GetFollowerCount(o, steamID);
            else
                return o(steamID);
        }(m_proxy);
    }

    SteamAPICall_t IsFollowing(CSteamID steamID) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::IsFollowing>(m_original);
            if constexpr (requires { p->IsFollowing(o, steamID); })
                return p->IsFollowing(o, steamID);
            else
                return o(steamID);
        }(m_proxy);
    }

    SteamAPICall_t EnumerateFollowingList(uint32 unStartIndex) override
    {
        return [&](auto p) -> SteamAPICall_t
        {
            auto o = MakeOrig<&ISteamFriends015::EnumerateFollowingList>(m_original);
            if constexpr (requires { p->EnumerateFollowingList(o, unStartIndex); })
                return p->EnumerateFollowingList(o, unStartIndex);
            else
                return o(unStartIndex);
        }(m_proxy);
    }
};

#endif // STEAMFRIENDSPROXY015_H
